# https://crusat.ru/blog/105-kak-proshe-vsego-razvernut-django-proekt-cherez-do/

# Способ создания "одноразовых" команд в Django через Docker:
# Создание изменений в модели. Те создание миграции. docker-compose run --rm web python manage.py makemigrations
# Провести/отменить миграцию. docker-compose run --rm web python manage.py migrate
# Создать суперпользователя. docker-compose run --rm web python manage.py createsuperuser

version: "3.9"
   
services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      